# Generated by Django 3.1.13 on 2023-11-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardrows',
            name='cash',
            field=models.IntegerField(default='0', verbose_name='Cash'),
        ),
    ]
