# Generated by Django 3.1.13 on 2023-11-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0002_dashboardrows_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardrows',
            name='points',
            field=models.IntegerField(default='0', verbose_name='Points'),
        ),
    ]
